name: Develop CI

on:
  release:
    types: [published]

env:
  APP_NAME: web.document.tcm

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set date as environment variable
      run: echo "DATETIME=$(date +"%Y%m%d")" >> $GITHUB_ENV
    - name: Docker login
      uses: docker/login-action@v1
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        registry: ${{ vars.DOCKERHUB_REGISTRY }}
        logout: true
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ vars.DOCKERHUB_REGISTRY }}/${{vars.DOCKERHUB_NAMESPACE}}/${{env.APP_NAME}}:${{github.event.release.tag_name}}_${{env.DATETIME}}
    - name: Docker image push
      run: docker push ${{ vars.DOCKERHUB_REGISTRY }}/${{vars.DOCKERHUB_NAMESPACE}}/${{env.APP_NAME}}:${{github.event.release.tag_name}}_${{env.DATETIME}}
